openapi: 3.0.3
info:
  title: Supplier Onboarding
  description: This is an open API documentation of the Supplier Onboarding BFF available APIs
  version: 0.0.1
  contact:
    email: supplieronboarding@taulia.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://supplier-onboarding
security:
  - apiKey: [ ]
paths:
  /api/v0.1/suppliers/{supplierId}:
    get:
      tags:
        - supplier
      security:
        - ApiKeyAuth: [ ]
      summary: Retrieves the Supplier representation for FE based on its id
      description: Retrieves Supplier representation for FE to be used in the onboarding process based on its id in order to prepopulate form fields
      operationId: getLegalEntity
      parameters:
        - in: path
          name: supplierId
          description: Id of the Supplier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          $ref: '#/components/responses/SupplierOk'
        401:
          $ref: "#/components/responses/UnauthorizedError"
        404:
          $ref: "#/components/responses/SupplierNotFound"
    post:
      tags:
        - supplier
      security:
        - ApiKeyAuth: [ ]
      summary: Updates the Supplier based on its id
      description: Updates Supplier data used in the onboarding process based on the FE posted data and returns the updated resource representation
      operationId: updateLegalEntity
      parameters:
        - in: path
          name: supplierId
          description: Id of the Supplier
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Supplier'
      #        required: true
      responses:
        200:
          $ref: '#/components/responses/SupplierOk'
        401:
          $ref: "#/components/responses/UnauthorizedError"
        404:
          $ref: "#/components/responses/SupplierNotFound"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-tau-rest-apikey

  schemas:
    Supplier:
      type: object
      properties:
        id:
          type: string
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        legalEntity:
          $ref: '#/components/schemas/LegalEntity'
        annualRevenue:
          $ref: '#/components/schemas/MonetaryValue'
        clasification:
          $ref: '#/components/schemas/Classification'
        contacts:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/Contact'
              - $ref: '#/components/schemas/Officer'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'

    LegalEntity:
      type: object
      properties:
        name:
          type: string
          example: Taulia, Inc
        tradeNames:
          type: string
          example: Taulia
        businessType:
          type: string
          enum:
            - Corporation
            - Business
            - Other
          default: Corporation
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
        taxId:
          type: string
          example: 123456789

    Person:
      type: object
      discriminator:
        propertyName: personType
        mapping:
          officer: '#/components/schemas/Officer'
          contact: '#/components/schemas/Contact'
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
          example: Andrei
        lastName:
          type: string
          example: Tataru
        personType:
          type: string
          example: One of Officer, Contact
      required:
        - personType

    Officer:
      type: object
      allOf:
        - $ref: '#/components/schemas/Person'
      properties:
        address:
          $ref: '#/components/schemas/Address'

    Contact:
      type: object
      allOf:
        - $ref: '#/components/schemas/Person'
      properties:
        phone:
          type: string
          example: 07600000
        email:
          type: string
          format: email

    Document:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Incumbency Certificate
        fileName:
          type: string
          example: inbumb_cert.pdf
        fileSize:
          type: number
          format: double
          example: 3.83
          description: Size of the file in KB
        createdDate:
          type: string
          format: date-time
          example: '2022-03-09T22:11:37.311Z'

    Jurisdiction:
      type: object
      properties:
        countryCode:
          type: string
          example: DE
        regionCode:
          type: string
          example: MUN
    Address:
      type: object
      properties:
        addressLine:
          type: string
          example: Str Stefan, ap 99, Brasov
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
    MonetaryValue:
      type: object
      properties:
        curencyCode:
          type: string
          enum:
            - USD
            - EUR
          example: EUR
        value:
          type: number
          format: double
          example: 21013.34
    Choice:
      type: string
      enum:
        - 'NO'
        - 'YES'
        - I_DO_NOT_KNOW
    Classification:
      type: object
      properties:
        ownerByMinority:
          $ref: '#/components/schemas/Choice'
        ownedByWomen:
          $ref: '#/components/schemas/Choice'
        smallOrMedium:
          $ref: '#/components/schemas/Choice'
        environmentalSocialGovernanceRated:
          $ref: '#/components/schemas/Choice'

  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
    SupplierNotFound:
      description: Supplier not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    SupplierOk:
      description: Supplier representation for FE
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Supplier'
