openapi: 3.0.3
info:
  title: Supplier Model
  description: This is an open API documentation of the Supplier Model
  version: 0.0.1
  contact:
    email: supplieronboarding@taulia.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://supplier-onboarding
paths:
  /api/v0/suppliers/{supplierId}:
    get:
      tags:
        - supplier
      summary: Retrieves the Supplier data model representation based on its id
      description: Retrieves Supplier data model
      operationId: getLegalEntity
      parameters:
        - in: path
          name: supplierId
          description: Id of the Supplier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Supplier representation for FE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'

        404:
          description: Supplier not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Supplier:
      type: object
      properties:
        id:
          type: string
          format: uuid
        programName:
          type: string
        supplierCompanyLegalName:
          type: string
        intialContact:
          type: array
          items:
            $ref: '#/components/schemas/InitialContact'
        additionalContact:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalContact'
        programEnglishName:
          type: string
        incorporationCountryCode:
          type: string
        incorporationState:
          type: string
        incorporationTerritory:
          type: string
        invoiceCurrencies:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceCurrencies'
        tradeOrDBANames:
          type: array
          items:
            $ref: '#/components/schemas/TradeOrDBANames'
        organizationType:
          type: number
        taxId:
          type: string
        estimatedAnnualSales:
          type: array
          items:
            $ref: '#/components/schemas/EstimatedAnnualSales'
        lienInterestReqCheck:
          type: boolean
        lienDetails:
          type: string
        supplierPolandInfo:
          type: array
          items:
            $ref: '#/components/schemas/SupplierPolandInfo'
        companyAddresses:
          type: array
          items:
            $ref: '#/components/schemas/CompanyAddresses'
        authorizedSigners:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizedSigners'
        discountElection:
          type: string
        numberOfAuthorizedSigners:
          type: integer

    AuthorizedSigners:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        title:
          type: string
        emailAddress:
          type: string
        phoneNumber:
          type: string
        manageAccess:
          type: boolean
    CompanyAddresses:
      type: object
      properties:
        addressType:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        country:
          type: string
        state:
          type: string
        city:
          type: string
        zipCode:
          type: string
        phone:
          type: string
        attention:
          type: string
    SupplierPolandInfo:
      type: object
      properties:
        splitPaymentCheck:
          type: boolean
        activeVatPayer:
          type: boolean
        bankAccNumForPolishTaxReg:
          type: string
        polishVatSplitPayment:
          type: boolean
    EstimatedAnnualSales:
      type: object
      properties:
        salesCurrencyCode:
          type: string
        annualSalesVolume:
          type: number
        currentPaymentTerms:
          type: string
        productsServices:
          type: string
    TradeOrDBANames:
      type: object
      properties:
        companyName:
          type: string
    InvoiceCurrencies:
      type: object
      properties:
        primaryInvoiceCurrency:
          type: string
        otherInvoiceCurrency:
          type: string
    InitialContact:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        title:
          type: string
        emailAddress:
          type: string
        phoneNumber:
          type: string
        manageAccess:
          type: string
    AdditionalContact:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        title:
          type: string
        emailAddress:
          type: string
        phoneNumber:
          type: string
        manageAccess:
          type: boolean