version: '3.9'

services:

  mysql:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/user_schema_init.sql:/docker-entrypoint-initdb.d/user_schema_init.sql
    ports:
      - "3306:3306"
    networks:
      - protal-net
    environment:
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=password
      #      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=backend
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  protal-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
