version: '3.4'

services:

  postgres:
    image: arm64v8/postgres:14-alpine
    volumes:
      - ./postgres/user_schema_init.sql:/docker-entrypoint-initdb.d/user_schema_init.sql
    #      - ./postgres/postgresql.conf:/etc/postgresql.conf
    #    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - protal-net
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=backend", "--host=127.0.0.1", "--port=5432" ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

  zookeeper:
    image: arm64v8/zookeeper:3.7.0
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - protal-net

  kafka:
    image: bitnami/kafka:2.6.0
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - protal-net

  unleash:
    image: unleashorg/unleash-server:4.7.2
    ports:
      - "4242:4242"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=backend
      - DATABASE_SCHEMA=unleash
      - DATABASE_USERNAME=backend
      - DATABASE_PASSWORD=password
      - DATABASE_SSL=false
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=unleash4all
    depends_on:
      - postgres
    networks:
      - protal-net
    healthcheck:
      test: [ "CMD", "nc",  "-z", "db", "5432" ]
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s


networks:
  protal-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
